site_name: Corelia Documentation
site_description: Documentation for Corelia project
site_author: "[Hicham](https://www.linkedin.com/in/hicham-djebali/)"
site_url: https://medaille-fr.github.io/corelia

# Repository
repo_name: medaille-fr/corelia
repo_url: https://github.com/medaille-fr/corelia
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  logo: docs/assets/logos/white.png
  favicon: docs/assets/logos/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter Tight
    code: JetBrains Mono

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_modification_date: true
      show_timezone: true
      timezone: Europe/Paris

# Extra CSS
extra_css:
  - stylesheets/extra.css


# Navigation
nav:
  - Home: index.md
  - Overview: overview.md
  - Architecture: architecture.md
  - Research Insights: research-insights.md
  - Datasets: datasets.md
  - Security & Compliance: security-compliance.md
  - Competitive Advantage: competitive-advantage.md
