# Mistral-7B Fine-tuning Configuration

model:
  name: "mistralai/Mistral-7B-Instruct-v0.1"
  max_length: 2048
  device_map: "auto"
  torch_dtype: "float16"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  output_dir: "./models/mistral-7b-lora"
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: true
  dataloader_num_workers: 4
  remove_unused_columns: false

datasets:
  train:
    - name: "chapin/NACHOS_large"
      weight: 0.5
    - name: "Abirate/mediqal"
      weight: 0.25
    - name: "alicelacaille/FRASIMED"
      weight: 0.15
    - name: "clinical_notes_corpus"
      weight: 0.1

mlflow:
  experiment_name: "mistral-7b-french-medical"
  tracking_uri: "file:./mlruns"
  log_models: true
